version: '3.8'
services:
  backend:
    build: ./backend
    ports: ["3000:3000"]
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/idp_db
    depends_on: [postgres]

  frontend:
    build: ./frontend
    ports: ["8080:80"]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: idp_db
    ports: ["5432:5432"]